language: ruby

rvm:
  - 2.5.1

before_script:
 - mkdir ~/.task
 - echo data.location=~/.task > ~/.taskrc

before_install:

before_install:
 - sudo apt-get update
 - sudo apt-get install task
 - sudo apt-get install graphviz

 # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-377680126
 - gem install bundler
